

english = {
    u"Hong Kong Island": {
        u"Chung Wan": u"a01",
        u"Mid Levels East": u"a02",
        u"Castle Road": u"a03",
        u"Peak": u"a04",
        u"University": u"a05",
        u"Kennedy Town & Mount Davis": u"a06",
        u"Kwun Lung": u"a07",
        u"Sai Wan": u"a08",
        u"Belcher": u"a09",
        u"Shek Tong Tsui": u"a10",
        u"Sai Ying Pun": u"a11",
        u"Sheung Wan": u"a12",
        u"Tung Wah": u"a13",
        u"Centre Street": u"a14",
        u"Water Street": u"a15",
        u"Hennessy": u"b01",
        u"Oi Kwan": u"b02",
        u"Canal Road": u"b03",
        u"Causeway Bay": u"b04",
        u"Tai Hang": u"b05",
        u"Jardine's Lookout": u"b06",
        u"Broadwood": u"b07",
        u"Happy Valley": u"b08",
        u"Stubbs Road": u"b09",
        u"Southorn": u"b10",
        u"Tai Fat Hau": u"b11",
        u"Tai Koo Shing West": u"c01",
        u"Tai Koo Shing East": u"c02",
        u"Lei King Wan": u"c03",
        u"Aldrich Bay": u"c04",
        u"Shaukeiwan": u"c05",
        u"A Kung Ngam": u"c06",
        u"Heng Fa Chuen": u"c07",
        u"Tsui Wan": u"c08",
        u"Yan Lam": u"c09",
        u"Siu Sai Wan": u"c10",
        u"King Yee": u"c11",
        u"Wan Tsui": u"c12",
        u"Fei Tsui": u"c13",
        u"Mount Parker": u"c14",
        u"Braemar Hill": u"c15",
        u"Tin Hau": u"c16",
        u"Fortress Hill": u"c17",
        u"Victoria Park": u"c18",
        u"City Garden": u"c19",
        u"Provident": u"c20",
        u"Fort Street": u"c21",
        u"Kam Ping": u"c22",
        u"Tanner": u"c23",
        u"Healthy Village": u"c24",
        u"Quarry Bay": u"c25",
        u"Nam Fung": u"c26",
        u"Kornhill": u"c27",
        u"Kornhill Garden": u"c28",
        u"Hing Tung": u"c29",
        u"Sai Wan Ho": u"c30",
        u"Lower Yiu Tung": u"c31",
        u"Upper Yiu Tung": u"c32",
        u"Hing Man": u"c33",
        u"Lok Hong": u"c34",
        u"Tsui Tak": u"c35",
        u"Yue Wan": u"c36",
        u"Kai Hiu": u"c37",
        u"Aberdeen": u"d01",
        u"Ap Lei Chau Estate": u"d02",
        u"Ap Lei Chau North": u"d03",
        u"Lei Tung I": u"d04",
        u"Lei Tung II": u"d05",
        u"South Horizons East": u"d06",
        u"South Horizons West": u"d07",
        u"Wah Kwai": u"d08",
        u"Wah Fu I": u"d09",
        u"Wah Fu II": u"d10",
        u"Pokfulam": u"d11",
        u"Chi Fu": u"d12",
        u"Tin Wan": u"d13",
        u"Shek Yue": u"d14",
        u"Wong Chuk Hang": u"d15",
        u"Bays Area": u"d16",
        u"Stanley & Shek O": u"d17"
    },
    u"Central and Western": {
        u"Chung Wan": u"a01",
        u"Mid Levels East": u"a02",
        u"Castle Road": u"a03",
        u"Peak": u"a04",
        u"University": u"a05",
        u"Kennedy Town & Mount Davis": u"a06",
        u"Kwun Lung": u"a07",
        u"Sai Wan": u"a08",
        u"Belcher": u"a09",
        u"Shek Tong Tsui": u"a10",
        u"Sai Ying Pun": u"a11",
        u"Sheung Wan": u"a12",
        u"Tung Wah": u"a13",
        u"Centre Street": u"a14",
        u"Water Street": u"a15"
    },
    u"Wan Chai": {
        u"Hennessy": u"b01",
        u"Oi Kwan": u"b02",
        u"Canal Road": u"b03",
        u"Causeway Bay": u"b04",
        u"Tai Hang": u"b05",
        u"Jardine's Lookout": u"b06",
        u"Broadwood": u"b07",
        u"Happy Valley": u"b08",
        u"Stubbs Road": u"b09",
        u"Southorn": u"b10",
        u"Tai Fat Hau": u"b11"
    },
    u"Eastern": {
        u"Tai Koo Shing West": u"c01",
        u"Tai Koo Shing East": u"c02",
        u"Lei King Wan": u"c03",
        u"Aldrich Bay": u"c04",
        u"Shaukeiwan": u"c05",
        u"A Kung Ngam": u"c06",
        u"Heng Fa Chuen": u"c07",
        u"Tsui Wan": u"c08",
        u"Yan Lam": u"c09",
        u"Siu Sai Wan": u"c10",
        u"King Yee": u"c11",
        u"Wan Tsui": u"c12",
        u"Fei Tsui": u"c13",
        u"Mount Parker": u"c14",
        u"Braemar Hill": u"c15",
        u"Tin Hau": u"c16",
        u"Fortress Hill": u"c17",
        u"Victoria Park": u"c18",
        u"City Garden": u"c19",
        u"Provident": u"c20",
        u"Fort Street": u"c21",
        u"Kam Ping": u"c22",
        u"Tanner": u"c23",
        u"Healthy Village": u"c24",
        u"Quarry Bay": u"c25",
        u"Nam Fung": u"c26",
        u"Kornhill": u"c27",
        u"Kornhill Garden": u"c28",
        u"Hing Tung": u"c29",
        u"Sai Wan Ho": u"c30",
        u"Lower Yiu Tung": u"c31",
        u"Upper Yiu Tung": u"c32",
        u"Hing Man": u"c33",
        u"Lok Hong": u"c34",
        u"Tsui Tak": u"c35",
        u"Yue Wan": u"c36",
        u"Kai Hiu": u"c37"
    },
    u"Southern": {
        u"Aberdeen": u"d01",
        u"Ap Lei Chau Estate": u"d02",
        u"Ap Lei Chau North": u"d03",
        u"Lei Tung I": u"d04",
        u"Lei Tung II": u"d05",
        u"South Horizons East": u"d06",
        u"South Horizons West": u"d07",
        u"Wah Kwai": u"d08",
        u"Wah Fu I": u"d09",
        u"Wah Fu II": u"d10",
        u"Pokfulam": u"d11",
        u"Chi Fu": u"d12",
        u"Tin Wan": u"d13",
        u"Shek Yue": u"d14",
        u"Wong Chuk Hang": u"d15",
        u"Bays Area": u"d16",
        u"Stanley & Shek O": u"d17"
    },
    u"Kowloon": {
        u"Tsim Sha Tsui West": u"e01",
        u"Jordan East": u"e02",
        u"Jordan West": u"e03",
        u"Yau Ma Tei": u"e04",
        u"Charming": u"e05",
        u"Mong Kok West": u"e06",
        u"Fu Pak": u"e07",
        u"Olympic": u"e08",
        u"Cherry": u"e09",
        u"Tai Kok Tsui South": u"e10",
        u"Tai Kok Tsui North": u"e11",
        u"Tai Nan": u"e12",
        u"Mong Kok North": u"e13",
        u"Mong Kok East": u"e14",
        u"Mong Kok South": u"e15",
        u"King's Park": u"e16",
        u"Tsim Sha Tsui East": u"e17",
        u"Po Lai": u"f01",
        u"Cheung Sha Wan": u"f02",
        u"Nam Cheong North": u"f03",
        u"Shek Kip Mei & Nam Cheong East": u"f04",
        u"Nam Cheong South": u"f05",
        u"Nam Cheong Central": u"f06",
        u"Nam Cheong West": u"f07",
        u"Fu Cheong": u"f08",
        u"Lai Kok": u"f09",
        u"Fortune": u"f10",
        u"Lai Chi Kok South": u"f11",
        u"Mei Foo South": u"f12",
        u"Mei Foo Central": u"f13",
        u"Mei Foo North": u"f14",
        u"Lai Chi Kok North": u"f15",
        u"Un Chau & So Uk": u"f16",
        u"Lei Cheng Uk": u"f17",
        u"Ha Pak Tin": u"f18",
        u"Yau Yat Tsuen": u"f19",
        u"Nam Shan, Tai Hang Tung & Tai Hang Sai": u"f20",
        u"Lung Ping & Sheung Pak Tin": u"f21",
        u"Ma Tau Wai": u"g01",
        u"Ma Hang Chung": u"g02",
        u"Ma Tau Kok": u"g03",
        u"Lok Man": u"g04",
        u"Sheung Lok": u"g05",
        u"Ho Man Tin": u"g06",
        u"Kadoorie": u"g07",
        u"Prince": u"g08",
        u"Kowloon Tong": u"g09",
        u"Lung Shing": u"g10",
        u"Kai Tak": u"g11",
        u"Hoi Sham": u"g12",
        u"To Kwa Wan North": u"g13",
        u"To Kwa Wan South": u"g14",
        u"Hok Yuen Laguna Verde": u"g15",
        u"Whampoa East": u"g16",
        u"Whampoa West": u"g17",
        u"Hung Hom Bay": u"g18",
        u"Hung Hom": u"g19",
        u"Ka Wai": u"g20",
        u"Oi Man": u"g21",
        u"Oi Chun": u"g22",
        u"Lung Tsui": u"h01",
        u"Lung Ha": u"h02",
        u"Lung Sheung": u"h03",
        u"Fung Wong": u"h04",
        u"Fung Tak": u"h05",
        u"Lung Sing": u"h06",
        u"San Po Kong": u"h07",
        u"Tung Tau": u"h08",
        u"Tung Mei": u"h09",
        u"Lok Fu": u"h10",
        u"Wang Tau Hom": u"h11",
        u"Tin Keung": u"h12",
        u"Tsui Chuk & Pang Ching": u"h13",
        u"Chuk Yuen South": u"h14",
        u"Chuk Yuen North": u"h15",
        u"Tsz Wan West": u"h16",
        u"Ching Oi": u"h17",
        u"Ching On": u"h18",
        u"Tsz Wan East": u"h19",
        u"King Fu": u"h20",
        u"Choi Wan East": u"h21",
        u"Choi Wan South": u"h22",
        u"Choi Wan West": u"h23",
        u"Chi Choi": u"h24",
        u"Choi Hung": u"h25",
        u"Kwun Tong Central": u"j01",
        u"Kowloon Bay": u"j02",
        u"Kai Yip": u"j03",
        u"Lai Ching": u"j04",
        u"Ping Shek": u"j05",
        u"Sheung Choi": u"j06",
        u"Jordan Valley": u"j07",
        u"Shun Tin": u"j08",
        u"Sheung Shun": u"j09",
        u"On Lee": u"j10",
        u"Po Tat": u"j11",
        u"Sau Mau Ping North": u"j12",
        u"Hiu Lai": u"j13",
        u"Sau Mau Ping South": u"j14",
        u"Hing Tin": u"j15",
        u"Lam Tin": u"j16",
        u"Kwong Tak": u"j17",
        u"Ping Tin": u"j18",
        u"Pak Nga": u"j19",
        u"Yau Tong East": u"j20",
        u"Yau Lai": u"j21",
        u"Chui Cheung": u"j22",
        u"Yau Tong West": u"j23",
        u"Laguna City": u"j24",
        u"King Tin": u"j25",
        u"Tsui Ping": u"j26",
        u"Po Lok": u"j27",
        u"Yuet Wah": u"j28",
        u"Hip Hong": u"j29",
        u"Hong Lok": u"j30",
        u"Ting On": u"j31",
        u"Ngau Tau Kok": u"j32",
        u"To Tai": u"j33",
        u"Lok Wah North": u"j34",
        u"Lok Wah South": u"j35"
    },
    u"Yau Tsim Mong": {
        u"Tsim Sha Tsui West": u"e01",
        u"Jordan East": u"e02",
        u"Jordan West": u"e03",
        u"Yau Ma Tei": u"e04",
        u"Charming": u"e05",
        u"Mong Kok West": u"e06",
        u"Fu Pak": u"e07",
        u"Olympic": u"e08",
        u"Cherry": u"e09",
        u"Tai Kok Tsui South": u"e10",
        u"Tai Kok Tsui North": u"e11",
        u"Tai Nan": u"e12",
        u"Mong Kok North": u"e13",
        u"Mong Kok East": u"e14",
        u"Mong Kok South": u"e15",
        u"King's Park": u"e16",
        u"Tsim Sha Tsui East": u"e17"
    },
    u"Sham Shui Po": {
        u"Po Lai": u"f01",
        u"Cheung Sha Wan": u"f02",
        u"Nam Cheong North": u"f03",
        u"Shek Kip Mei & Nam Cheong East": u"f04",
        u"Nam Cheong South": u"f05",
        u"Nam Cheong Central": u"f06",
        u"Nam Cheong West": u"f07",
        u"Fu Cheong": u"f08",
        u"Lai Kok": u"f09",
        u"Fortune": u"f10",
        u"Lai Chi Kok South": u"f11",
        u"Mei Foo South": u"f12",
        u"Mei Foo Central": u"f13",
        u"Mei Foo North": u"f14",
        u"Lai Chi Kok North": u"f15",
        u"Un Chau & So Uk": u"f16",
        u"Lei Cheng Uk": u"f17",
        u"Ha Pak Tin": u"f18",
        u"Yau Yat Tsuen": u"f19",
        u"Nam Shan, Tai Hang Tung & Tai Hang Sai": u"f20",
        u"Lung Ping & Sheung Pak Tin": u"f21"
    },
    u"Kowloon City": {
        u"Ma Tau Wai": u"g01",
        u"Ma Hang Chung": u"g02",
        u"Ma Tau Kok": u"g03",
        u"Lok Man": u"g04",
        u"Sheung Lok": u"g05",
        u"Ho Man Tin": u"g06",
        u"Kadoorie": u"g07",
        u"Prince": u"g08",
        u"Kowloon Tong": u"g09",
        u"Lung Shing": u"g10",
        u"Kai Tak": u"g11",
        u"Hoi Sham": u"g12",
        u"To Kwa Wan North": u"g13",
        u"To Kwa Wan South": u"g14",
        u"Hok Yuen Laguna Verde": u"g15",
        u"Whampoa East": u"g16",
        u"Whampoa West": u"g17",
        u"Hung Hom Bay": u"g18",
        u"Hung Hom": u"g19",
        u"Ka Wai": u"g20",
        u"Oi Man": u"g21",
        u"Oi Chun": u"g22"
    },
    u"Wong Tai Sin": {
        u"Lung Tsui": u"h01",
        u"Lung Ha": u"h02",
        u"Lung Sheung": u"h03",
        u"Fung Wong": u"h04",
        u"Fung Tak": u"h05",
        u"Lung Sing": u"h06",
        u"San Po Kong": u"h07",
        u"Tung Tau": u"h08",
        u"Tung Mei": u"h09",
        u"Lok Fu": u"h10",
        u"Wang Tau Hom": u"h11",
        u"Tin Keung": u"h12",
        u"Tsui Chuk & Pang Ching": u"h13",
        u"Chuk Yuen South": u"h14",
        u"Chuk Yuen North": u"h15",
        u"Tsz Wan West": u"h16",
        u"Ching Oi": u"h17",
        u"Ching On": u"h18",
        u"Tsz Wan East": u"h19",
        u"King Fu": u"h20",
        u"Choi Wan East": u"h21",
        u"Choi Wan South": u"h22",
        u"Choi Wan West": u"h23",
        u"Chi Choi": u"h24",
        u"Choi Hung": u"h25"
    },
    u"Kwun Tong": {
        u"Kwun Tong Central": u"j01",
        u"Kowloon Bay": u"j02",
        u"Kai Yip": u"j03",
        u"Lai Ching": u"j04",
        u"Ping Shek": u"j05",
        u"Sheung Choi": u"j06",
        u"Jordan Valley": u"j07",
        u"Shun Tin": u"j08",
        u"Sheung Shun": u"j09",
        u"On Lee": u"j10",
        u"Po Tat": u"j11",
        u"Sau Mau Ping North": u"j12",
        u"Hiu Lai": u"j13",
        u"Sau Mau Ping South": u"j14",
        u"Hing Tin": u"j15",
        u"Lam Tin": u"j16",
        u"Kwong Tak": u"j17",
        u"Ping Tin": u"j18",
        u"Pak Nga": u"j19",
        u"Yau Tong East": u"j20",
        u"Yau Lai": u"j21",
        u"Chui Cheung": u"j22",
        u"Yau Tong West": u"j23",
        u"Laguna City": u"j24",
        u"King Tin": u"j25",
        u"Tsui Ping": u"j26",
        u"Po Lok": u"j27",
        u"Yuet Wah": u"j28",
        u"Hip Hong": u"j29",
        u"Hong Lok": u"j30",
        u"Ting On": u"j31",
        u"Ngau Tau Kok": u"j32",
        u"To Tai": u"j33",
        u"Lok Wah North": u"j34",
        u"Lok Wah South": u"j35",
        },
    u"New Territories": {
        u"Tak Wah": u"k01",
        u"Yeung Uk Road": u"k02",
        u"Hoi Bun": u"k03",
        u"Clague Garden": u"k04",
        u"Fuk Loi": u"k05",
        u"Discovery Park": u"k06",
        u"Tsuen Wan Centre": u"k07",
        u"Allway": u"k08",
        u"Lai To": u"k09",
        u"Lai Hing": u"k10",
        u"Tsuen Wan Rural West": u"k11",
        u"Tsuen Wan Rural East": u"k12",
        u"Luk Yeung": u"k13",
        u"Lei Muk Shue East": u"k14",
        u"Lei Muk Shue West": u"k15",
        u"Shek Wai Kok": u"k16",
        u"Cheung Shek": u"k17",
        u"Tuen Mun Town Centre": u"l01",
        u"Siu Chi": u"l02",
        u"Siu Tsui": u"l03",
        u"On Ting": u"l04",
        u"Yau Oi South": u"l05",
        u"Yau Oi North": u"l06",
        u"Tsui Hing": u"l07",
        u"Shan King": u"l08",
        u"King Hing": u"l09",
        u"Hing Tsak": u"l10",
        u"San Hui": u"l11",
        u"Sam Shing": u"l12",
        u"Hanford": u"l13",
        u"Fu Sun": u"l14",
        u"Yuet Wu": u"l15",
        u"Siu Hei": u"l16",
        u"Wu King": u"l17",
        u"Butterfly": u"l18",
        u"Lok Tsui": u"l19",
        u"Lung Mun": u"l20",
        u"San King": u"l21",
        u"Leung King": u"l22",
        u"Tin King": u"l23",
        u"Po Tin": u"l24",
        u"Kin Sang": u"l25",
        u"Siu Hong": u"l26",
        u"Prime View": u"l27",
        u"Fu Tai": u"l28",
        u"Tuen Mun Rural": u"l29",
        u"Fung Nin": u"m01",
        u"Shui Pin": u"m02",
        u"Nam Ping": u"m03",
        u"Pek Long": u"m04",
        u"Yuen Long Centre": u"m05",
        u"Fung Cheung": u"m06",
        u"Shap Pat Heung North": u"m07",
        u"Shap Pat Heung South": u"m08",
        u"Ping Shan South": u"m09",
        u"Ping Shan North": u"m10",
        u"Ha Tsuen": u"m11",
        u"Tin Shing": u"m12",
        u"Shui Oi": u"m13",
        u"Shui Wah": u"m14",
        u"Chung Wah": u"m15",
        u"Yuet Yan": u"m16",
        u"Fu Yan": u"m17",
        u"Yat Chak": u"m18",
        u"Tin Heng": u"m19",
        u"Wang Yat": u"m20",
        u"Ching King": u"m21",
        u"Kingswood North": u"m22",
        u"Tsz Yau": u"m23",
        u"Tin Yiu": u"m24",
        u"Kingswood South": u"m25",
        u"Chung Pak": u"m26",
        u"Fairview Park": u"m27",
        u"San Tin": u"m28",
        u"Kam Tin": u"m29",
        u"Pat Heung North": u"m30",
        u"Pat Heung South": u"m31",
        u"Luen Wo Hui": u"n01",
        u"Fanling Town": u"n02",
        u"Cheung Wah": u"n03",
        u"Wah Do": u"n04",
        u"Wah Ming": u"n05",
        u"Yan Shing": u"n06",
        u"Shing Fuk": u"n07",
        u"Sheung Shui Rural": u"n08",
        u"Ching Ho": u"n09",
        u"Yu Tai": u"n10",
        u"Choi Yuen": u"n11",
        u"Shek Wu Hui": u"n12",
        u"Tin Ping West": u"n13",
        u"Fung Tsui": u"n14",
        u"Sha Ta": u"n15",
        u"Tin Ping East": u"n16",
        u"Queen's Hill": u"n17",
        u"Tai Po Hui": u"p01",
        u"Tai Po Central": u"p02",
        u"Chung Ting": u"p03",
        u"Tai Yuen": u"p04",
        u"Fu Heng": u"p05",
        u"Yee Fu": u"p06",
        u"Fu Ming Sun": u"p07",
        u"Kwong Fuk & Plover Cove": u"p08",
        u"Wang Fuk": u"p09",
        u"Tai Po Kau": u"p10",
        u"Wan Tau Tong": u"p11",
        u"San Fu": u"p12",
        u"Lam Tsuen Valley": u"p13",
        u"Po Nga": u"p14",
        u"Tai Wo": u"p15",
        u"Old Market & Serenity": u"p16",
        u"Hong Lok Yuen": u"p17",
        u"Shuen Wan": u"p18",
        u"Sai Kung North": u"p19",
        u"Sai Kung Central": u"q01",
        u"Pak Sha Wan": u"q02",
        u"Sai Kung Islands": u"q03",
        u"Hang Hau East": u"q04",
        u"Hang Hau West": u"q05",
        u"Po Kwan": u"q06",
        u"Wai Do": u"q07",
        u"Kin Shin": u"q08",
        u"Choi Kin": u"q09",
        u"O Tong": u"q10",
        u"Fu Kwan": u"q11",
        u"Nam On": u"q12",
        u"Hong King": u"q13",
        u"Tsui Lam": u"q14",
        u"Po Lam": u"q15",
        u"Yan Ying": u"q16",
        u"Wan Hang": u"q17",
        u"King Lam": u"q18",
        u"Hau Tak": u"q19",
        u"Fu Nam": u"q20",
        u"Tak Ming": u"q21",
        u"Sheung Tak": u"q22",
        u"Kwong Ming": u"q23",
        u"Wan Po": u"q24",
        u"Sha Tin Town Centre": u"r01",
        u"Lek Yuen": u"r02",
        u"Wo Che Estate": u"r03",
        u"City One": u"r04",
        u"Yue Shing": u"r05",
        u"Wong Uk": u"r06",
        u"Sha Kok": u"r07",
        u"Pok Hong": u"r08",
        u"Jat Min": u"r09",
        u"Chun Fung": u"r10",
        u"Sun Tin Wai": u"r11",
        u"Chui Tin": u"r12",
        u"Hin Ka": u"r13",
        u"Lower Shing Mun": u"r14",
        u"Keng Hau": u"r15",
        u"Tin Sum": u"r16",
        u"Chui Ka": u"r17",
        u"Tai Wai": u"r18",
        u"Chung Tin": u"r19",
        u"Sui Wo": u"r20",
        u"Fo Tan": u"r21",
        u"Chun Ma": u"r22",
        u"Chung On": u"r23",
        u"Kam To": u"r24",
        u"Ma On Shan Town Centre": u"r25",
        u"Lee On": u"r26",
        u"Fu Lung": u"r27",
        u"Kam Ying": u"r28",
        u"Yiu On": u"r29",
        u"Heng On": u"r30",
        u"On Tai": u"r31",
        u"Tai Shui Hang": u"r32",
        u"Yu Yan": u"r33",
        u"Bik Woo": u"r34",
        u"Kwong Hong": u"r35",
        u"Kwong Yuen": u"r36",
        u"Kwai Hing": u"s01",
        u"Kwai Shing East Estate": u"s02",
        u"Upper Tai Wo Hau": u"s03",
        u"Lower Tai Wo Hau": u"s04",
        u"Kwai Chung Estate North": u"s05",
        u"Kwai Chung Estate Central": u"s06",
        u"Shek Yam": u"s07",
        u"On Yam": u"s08",
        u"Shek Lei Extension": u"s09",
        u"Shek Lei": u"s10",
        u"Tai Pak Tin": u"s11",
        u"Kwai Fong": u"s12",
        u"Wah Lai": u"s13",
        u"Lai Wah": u"s14",
        u"Cho Yiu": u"s15",
        u"Hing Fong": u"s16",
        u"Lai King": u"s17",
        u"Kwai Shing West Estate": u"s18",
        u"On Ho": u"s19",
        u"Wai Ying": u"s20",
        u"Tsing Yi Estate": u"s21",
        u"Greenfield": u"s22",
        u"Cheung Ching": u"s23",
        u"Cheung Hong": u"s24",
        u"Shing Hong": u"s25",
        u"Tsing Yi South": u"s26",
        u"Cheung Hang": u"s27",
        u"Ching Fat": u"s28",
        u"Cheung On": u"s29",
        u"Lantau": u"t01",
        u"Yat Tung Estate North": u"t02",
        u"Yat Tung Estate South": u"t03",
        u"Tung Chung North": u"t04",
        u"Tung Chung South": u"t05",
        u"Discovery Bay": u"t06",
        u"Peng Chau & Hei Ling Chau": u"t07",
        u"Lamma & Po Toi": u"t08",
        u"Cheung Chau South": u"t09",
        u"Cheung Chau North": u"t10"
    },
    u"Kwai Tsing": {
        u"Kwai Hing": u"s01",
        u"Kwai Shing East Estate": u"s02",
        u"Upper Tai Wo Hau": u"s03",
        u"Lower Tai Wo Hau": u"s04",
        u"Kwai Chung Estate North": u"s05",
        u"Kwai Chung Estate Central": u"s06",
        u"Shek Yam": u"s07",
        u"On Yam": u"s08",
        u"Shek Lei Extension": u"s09",
        u"Shek Lei": u"s10",
        u"Tai Pak Tin": u"s11",
        u"Kwai Fong": u"s12",
        u"Wah Lai": u"s13",
        u"Lai Wah": u"s14",
        u"Cho Yiu": u"s15",
        u"Hing Fong": u"s16",
        u"Lai King": u"s17",
        u"Kwai Shing West Estate": u"s18",
        u"On Ho": u"s19",
        u"Wai Ying": u"s20",
        u"Tsing Yi Estate": u"s21",
        u"Greenfield": u"s22",
        u"Cheung Ching": u"s23",
        u"Cheung Hong": u"s24",
        u"Shing Hong": u"s25",
        u"Tsing Yi South": u"s26",
        u"Cheung Hang": u"s27",
        u"Ching Fat": u"s28",
        u"Cheung On": u"s29"
    },
    u"Tsuen Wan": {
        u"Tak Wah": u"k01",
        u"Yeung Uk Road": u"k02",
        u"Hoi Bun": u"k03",
        u"Clague Garden": u"k04",
        u"Fuk Loi": u"k05",
        u"Discovery Park": u"k06",
        u"Tsuen Wan Centre": u"k07",
        u"Allway": u"k08",
        u"Lai To": u"k09",
        u"Lai Hing": u"k10",
        u"Tsuen Wan Rural West": u"k11",
        u"Tsuen Wan Rural East": u"k12",
        u"Luk Yeung": u"k13",
        u"Lei Muk Shue East": u"k14",
        u"Lei Muk Shue West": u"k15",
        u"Shek Wai Kok": u"k16",
        u"Cheung Shek": u"k17"
    },
    u"Tuen Mun": {
        u"Tuen Mun Town Centre": u"l01",
        u"Siu Chi": u"l02",
        u"Siu Tsui": u"l03",
        u"On Ting": u"l04",
        u"Yau Oi South": u"l05",
        u"Yau Oi North": u"l06",
        u"Tsui Hing": u"l07",
        u"Shan King": u"l08",
        u"King Hing": u"l09",
        u"Hing Tsak": u"l10",
        u"San Hui": u"l11",
        u"Sam Shing": u"l12",
        u"Hanford": u"l13",
        u"Fu Sun": u"l14",
        u"Yuet Wu": u"l15",
        u"Siu Hei": u"l16",
        u"Wu King": u"l17",
        u"Butterfly": u"l18",
        u"Lok Tsui": u"l19",
        u"Lung Mun": u"l20",
        u"San King": u"l21",
        u"Leung King": u"l22",
        u"Tin King": u"l23",
        u"Po Tin": u"l24",
        u"Kin Sang": u"l25",
        u"Siu Hong": u"l26",
        u"Prime View": u"l27",
        u"Fu Tai": u"l28",
        u"Tuen Mun Rural": u"l29"
    },
    u"Yuen Long": {
        u"Fung Nin": u"m01",
        u"Shui Pin": u"m02",
        u"Nam Ping": u"m03",
        u"Pek Long": u"m04",
        u"Yuen Long Centre": u"m05",
        u"Fung Cheung": u"m06",
        u"Shap Pat Heung North": u"m07",
        u"Shap Pat Heung South": u"m08",
        u"Ping Shan South": u"m09",
        u"Ping Shan North": u"m10",
        u"Ha Tsuen": u"m11",
        u"Tin Shing": u"m12",
        u"Shui Oi": u"m13",
        u"Shui Wah": u"m14",
        u"Chung Wah": u"m15",
        u"Yuet Yan": u"m16",
        u"Fu Yan": u"m17",
        u"Yat Chak": u"m18",
        u"Tin Heng": u"m19",
        u"Wang Yat": u"m20",
        u"Ching King": u"m21",
        u"Kingswood North": u"m22",
        u"Tsz Yau": u"m23",
        u"Tin Yiu": u"m24",
        u"Kingswood South": u"m25",
        u"Chung Pak": u"m26",
        u"Fairview Park": u"m27",
        u"San Tin": u"m28",
        u"Kam Tin": u"m29",
        u"Pat Heung North": u"m30",
        u"Pat Heung South": u"m31"
    },
    u"North": {
        u"Luen Wo Hui": u"n01",
        u"Fanling Town": u"n02",
        u"Cheung Wah": u"n03",
        u"Wah Do": u"n04",
        u"Wah Ming": u"n05",
        u"Yan Shing": u"n06",
        u"Shing Fuk": u"n07",
        u"Sheung Shui Rural": u"n08",
        u"Ching Ho": u"n09",
        u"Yu Tai": u"n10",
        u"Choi Yuen": u"n11",
        u"Shek Wu Hui": u"n12",
        u"Tin Ping West": u"n13",
        u"Fung Tsui": u"n14",
        u"Sha Ta": u"n15",
        u"Tin Ping East": u"n16",
        u"Queen's Hill": u"n17"
    },
    u"Tai Po": {
        u"Tai Po Hui": u"p01",
        u"Tai Po Central": u"p02",
        u"Chung Ting": u"p03",
        u"Tai Yuen": u"p04",
        u"Fu Heng": u"p05",
        u"Yee Fu": u"p06",
        u"Fu Ming Sun": u"p07",
        u"Kwong Fuk & Plover Cove": u"p08",
        u"Wang Fuk": u"p09",
        u"Tai Po Kau": u"p10",
        u"Wan Tau Tong": u"p11",
        u"San Fu": u"p12",
        u"Lam Tsuen Valley": u"p13",
        u"Po Nga": u"p14",
        u"Tai Wo": u"p15",
        u"Old Market & Serenity": u"p16",
        u"Hong Lok Yuen": u"p17",
        u"Shuen Wan": u"p18",
        u"Sai Kung North": u"p19"
    },
    u"Sha Tin": {
        u"Sha Tin Town Centre": u"r01",
        u"Lek Yuen": u"r02",
        u"Wo Che Estate": u"r03",
        u"City One": u"r04",
        u"Yue Shing": u"r05",
        u"Wong Uk": u"r06",
        u"Sha Kok": u"r07",
        u"Pok Hong": u"r08",
        u"Jat Min": u"r09",
        u"Chun Fung": u"r10",
        u"Sun Tin Wai": u"r11",
        u"Chui Tin": u"r12",
        u"Hin Ka": u"r13",
        u"Lower Shing Mun": u"r14",
        u"Keng Hau": u"r15",
        u"Tin Sum": u"r16",
        u"Chui Ka": u"r17",
        u"Tai Wai": u"r18",
        u"Chung Tin": u"r19",
        u"Sui Wo": u"r20",
        u"Fo Tan": u"r21",
        u"Chun Ma": u"r22",
        u"Chung On": u"r23",
        u"Kam To": u"r24",
        u"Ma On Shan Town Centre": u"r25",
        u"Lee On": u"r26",
        u"Fu Lung": u"r27",
        u"Kam Ying": u"r28",
        u"Yiu On": u"r29",
        u"Heng On": u"r30",
        u"On Tai": u"r31",
        u"Tai Shui Hang": u"r32",
        u"Yu Yan": u"r33",
        u"Bik Woo": u"r34",
        u"Kwong Hong": u"r35",
        u"Kwong Yuen": u"r36"
    },
    u"Sai Kung": {
        u"Sai Kung Central": u"q01",
        u"Pak Sha Wan": u"q02",
        u"Sai Kung Islands": u"q03",
        u"Hang Hau East": u"q04",
        u"Hang Hau West": u"q05",
        u"Po Kwan": u"q06",
        u"Wai Do": u"q07",
        u"Kin Shin": u"q08",
        u"Choi Kin": u"q09",
        u"O Tong": u"q10",
        u"Fu Kwan": u"q11",
        u"Nam On": u"q12",
        u"Hong King": u"q13",
        u"Tsui Lam": u"q14",
        u"Po Lam": u"q15",
        u"Yan Ying": u"q16",
        u"Wan Hang": u"q17",
        u"King Lam": u"q18",
        u"Hau Tak": u"q19",
        u"Fu Nam": u"q20",
        u"Tak Ming": u"q21",
        u"Sheung Tak": u"q22",
        u"Kwong Ming": u"q23",
        u"Wan Po": u"q24"
    },
    u"Islands": {
        u"Lantau": u"t01",
        u"Yat Tung Estate North": u"t02",
        u"Yat Tung Estate South": u"t03",
        u"Tung Chung North": u"t04",
        u"Tung Chung South": u"t05",
        u"Discovery Bay": u"t06",
        u"Peng Chau & Hei Ling Chau": u"t07",
        u"Lamma & Po Toi": u"t08",
        u"Cheung Chau South": u"t09",
        u"Cheung Chau North": u"t10"
    },
}

import models
from google.appengine.ext import ndb
import logging


def populate_constituency_areas(*args, **kwargs):
    """
    Loads all of the constituency areas into the database
    """
    objs_to_commit = []
    for district, cas in english.items():
        for ca, code in cas.items():
            logging.info("Adding CA {} {}".format(code, ca))
            obj = models.ConstituencyArea(id=code, district=district, name_english=ca, code=code)
            objs_to_commit.append(obj)

    ndb.put_multi(objs_to_commit)
    return 'OK'
